name: "Bug Report"
description: Report a bug on AniTrack
labels:
body:
  - type: textarea
    id: problem
    attributes:
      label: Describe the problem
      description: Provide a clear and concise description of the problem you discovered. This is quite important for understanding what is generally wrong.
    validations:
      required: true
  - type: textarea
    id: reproducibility
    attributes:
      label: How to reproduce
      description: If you can't reproduce it, put a label called "Cant reproduce" and skip it. Describe how to reproduce the bug you found. Describe as accurately and in detail as possible.
    validations:
      required: false
