name: "Feature Request"
description: Request your solution to be added to AniTrack
labels:
body:
  - type: textarea
    id: problem
    attributes:
      label: Describe the problem
      description: Provide a clear and concise description of the problem you discovered. This is quite important for understanding what is generally wrong.
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution
      description: Explain clearly and concisely how you want to solve or how you have already solved the problem.
    validations:
      required: true
